os:
  - windows
  - linux
  - osx

language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; rustup component add rustfmt && cargo fmt --all -- --check; fi
  - cargo build --verbose
  - cargo test --verbose
